# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 80
        env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.name }}
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.name }}
              key: password
        volumeMounts:
        - name: my-volume
          mountPath: {{ .Values.volumeMount.path }}
        - name: my-configmap-volume
          mountPath: {{ .Values.configMap.path }}
      volumes:
      - name: my-volume
        persistentVolumeClaim:
          claimName: {{ .Values.persistentVolumeClaim.name }}
      - name: my-configmap-volume
        configMap:
          name: {{ .Values.configMap.name }}


