# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  username: dHVfdXNlcm5hbWU=  # valor codificado en base64
  password: dHVfY29udHJhc2XDsWE=  #  valor codificado en base64
