# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  username: dHVfdXNlcbWU=  # valor codificado en base64
  password: dHVfY29u2XDsWE=  #  valor codificado en base64
